# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Adapter for the ``terok_executor`` wheel.

Re-exports every symbol terok consumes from terok-executor.  Callers
elsewhere in terok import from this module rather than from
``terok_executor`` directly — see the package docstring in
[`terok.lib.integrations`][terok.lib.integrations] for the rationale.

Every symbol comes from the wheel's top-level public API.
"""

from terok_executor import (  # noqa: F401 — re-exported public API
    AGENT_COMMANDS,
    AGENT_PROVIDERS,
    AGENTS_LABEL,
    AUTH_PROVIDERS,
    COMMANDS,
    DEFAULT_BASE_IMAGE,
    PROVIDER_NAMES,
    VAULT_COMMANDS,
    ACPEndpointStatus,
    AgentConfigSpec,
    AgentProvider,
    AgentRoster,
    AgentRunner,
    BuildError,
    CLIOverrides,
    ContainerEnvSpec,
    ExecutorConfigView,
    RawImageSection,
    SharedMountStorageInfo,
    TaskStorageInfo,
    acp_socket_is_live,
    agent_doctor_checks,
    apply_provider_config,
    assemble_container_env,
    authenticate,
    build_base_images,
    build_headless_command,
    build_project_image,
    build_sidecar_image,
    bundled_default_instructions,
    collect_all_auto_approve_env,
    detect_family,
    ensure_default_l1,
    ensure_sandbox_ready,
    ensure_vault_routes,
    get_provider,
    get_roster,
    get_shared_mounts_storage,
    get_tasks_storage,
    image_agents,
    inject_prompt,
    l0_image_tag,
    l1_image_tag,
    list_authenticated_agents,
    make_krun_runtime,
    parse_agent_selection,
    parse_md_agent,
    prepare_agent_config_dir,
    render_l0,
    render_l1,
    resolve_instructions,
    resolve_provider_value,
    scan_leaked_credentials,
    seed_workspace_from_clone_cache,
    stage_scripts,
    stage_tmux_config,
    stage_toad_agents,
)

__all__ = [
    "ACPEndpointStatus",
    "AGENT_COMMANDS",
    "AGENT_PROVIDERS",
    "AGENTS_LABEL",
    "AUTH_PROVIDERS",
    "COMMANDS",
    "AgentConfigSpec",
    "AgentProvider",
    "AgentRoster",
    "AgentRunner",
    "BuildError",
    "CLIOverrides",
    "ContainerEnvSpec",
    "DEFAULT_BASE_IMAGE",
    "ExecutorConfigView",
    "PROVIDER_NAMES",
    "RawImageSection",
    "SharedMountStorageInfo",
    "TaskStorageInfo",
    "VAULT_COMMANDS",
    "acp_socket_is_live",
    "agent_doctor_checks",
    "apply_provider_config",
    "assemble_container_env",
    "authenticate",
    "build_base_images",
    "build_headless_command",
    "build_project_image",
    "build_sidecar_image",
    "bundled_default_instructions",
    "collect_all_auto_approve_env",
    "detect_family",
    "ensure_default_l1",
    "ensure_sandbox_ready",
    "ensure_vault_routes",
    "get_provider",
    "get_roster",
    "get_shared_mounts_storage",
    "get_tasks_storage",
    "image_agents",
    "inject_prompt",
    "l0_image_tag",
    "l1_image_tag",
    "list_authenticated_agents",
    "make_krun_runtime",
    "parse_agent_selection",
    "parse_md_agent",
    "prepare_agent_config_dir",
    "render_l0",
    "render_l1",
    "resolve_instructions",
    "resolve_provider_value",
    "scan_leaked_credentials",
    "seed_workspace_from_clone_cache",
    "stage_scripts",
    "stage_tmux_config",
    "stage_toad_agents",
]
