# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Adapter for the ``terok_sandbox`` wheel (and its re-exports of shield).

Re-exports every symbol terok consumes from terok-sandbox.  Callers
elsewhere in terok import from this module rather than from
``terok_sandbox`` directly — see the package docstring in
[`terok.lib.integrations`][terok.lib.integrations] for the rationale.

Every symbol comes from the wheel's top-level public API.  Shield's
high-level wrappers (``make_shield``, ``up``, ``down``, ``quarantine``,
``status``) flow through here as sandbox's own re-exports; shield's
command registry has its own adapter, ``terok.lib.integrations.shield``.

Foundation-layer symbols (``ConfigStack`` / ``ConfigScope`` /
``deep_merge``, ``namespace_state_dir`` / ``namespace_runtime_dir``)
do **not** flow through here — the adapter is the conduit for sibling
**wheels**, while [`terok_util`][terok_util] is a foundation library
imported directly by every layer that needs it.
"""

from terok_sandbox import (  # noqa: F401 — re-exported public API
    DEFAULT_GUEST_SSHD_PORT,
    DEFAULT_SSH_HOST,
    DEFAULT_SSH_USER,
    EXIT_MANUAL_STEP_NEEDED,
    GATE_COMMANDS,
    SERVICES_TCP_OPTOUT_YAML,
    SSH_COMMANDS,
    BestEffortLogger,
    CheckVerdict,
    CommandDef,
    CommandTree,
    ContainerRuntime,
    CredentialDB,
    DoctorCheck,
    EnvironmentCheck,
    ExecResult,
    FakeKrunTransport,
    GateAuthNotConfigured,
    GateServerManager,
    GateServerStatus,
    GateStalenessInfo,
    GitGate,
    Image,
    KrunRuntime,
    KrunTransport,
    LifecycleHooks,
    NoPassphraseError,
    NullRuntime,
    PodmanRuntime,
    RawHooksSection,
    RawRunSection,
    RawSSHSection,
    RecoveryStatus,
    Sandbox,
    SandboxConfig,
    SelinuxStatus,
    ServicesMode,
    SetupVerdict,
    Sharing,
    SSHInitResult,
    SSHManager,
    TcpEndpoint,
    TcpSSHTransport,
    TokenStore,
    VaultManager,
    VaultStatus,
    VaultUnreachableError,
    VolumeSpec,
    WrongPassphraseError,
    bold,
    check_environment,
    check_selinux_status,
    claim_port,
    down,
    ensure_infra_keypair,
    gate_use_personal_ssh_default,
    handle_vault_seal,
    handle_vault_to_keyring,
    installed_versions,
    is_ssh_url,
    is_systemd_creds_available,
    make_shield,
    needs_setup,
    podman_port_resolver,
    public_line_of,
    quarantine,
    read_stamp,
    red,
    release_port,
    resolve_container_state_dir,
    run_setup,
    sandbox_doctor_checks,
    sandbox_uninstall,
    selinux_install_command,
    selinux_install_script,
    setup_hooks_direct,
    shield_interactive_session,
    shield_watch_session,
    stage_line,
    stamp_path,
    state,
    status,
    systemd_creds_has_tpm2,
    up,
    yaml_update_section,
    yellow,
)

__all__ = [
    "BestEffortLogger",
    "CheckVerdict",
    "CommandDef",
    "CommandTree",
    "ContainerRuntime",
    "CredentialDB",
    "DEFAULT_GUEST_SSHD_PORT",
    "DEFAULT_SSH_HOST",
    "DEFAULT_SSH_USER",
    "DoctorCheck",
    "EXIT_MANUAL_STEP_NEEDED",
    "EnvironmentCheck",
    "ExecResult",
    "FakeKrunTransport",
    "GATE_COMMANDS",
    "GateAuthNotConfigured",
    "GateServerManager",
    "GateServerStatus",
    "GateStalenessInfo",
    "GitGate",
    "Image",
    "KrunRuntime",
    "KrunTransport",
    "LifecycleHooks",
    "NoPassphraseError",
    "NullRuntime",
    "PodmanRuntime",
    "RawHooksSection",
    "RawRunSection",
    "RawSSHSection",
    "SERVICES_TCP_OPTOUT_YAML",
    "SSH_COMMANDS",
    "SSHInitResult",
    "SSHManager",
    "Sandbox",
    "SandboxConfig",
    "SelinuxStatus",
    "ServicesMode",
    "SetupVerdict",
    "Sharing",
    "TcpEndpoint",
    "TcpSSHTransport",
    "TokenStore",
    "VaultManager",
    "VaultStatus",
    "VaultUnreachableError",
    "VolumeSpec",
    "WrongPassphraseError",
    "RecoveryStatus",
    "bold",
    "check_environment",
    "check_selinux_status",
    "claim_port",
    "down",
    "ensure_infra_keypair",
    "gate_use_personal_ssh_default",
    "handle_vault_seal",
    "handle_vault_to_keyring",
    "installed_versions",
    "is_ssh_url",
    "is_systemd_creds_available",
    "make_shield",
    "needs_setup",
    "podman_port_resolver",
    "public_line_of",
    "quarantine",
    "read_stamp",
    "red",
    "release_port",
    "resolve_container_state_dir",
    "run_setup",
    "sandbox_doctor_checks",
    "sandbox_uninstall",
    "selinux_install_command",
    "selinux_install_script",
    "setup_hooks_direct",
    "shield_interactive_session",
    "shield_watch_session",
    "stage_line",
    "stamp_path",
    "state",
    "status",
    "systemd_creds_has_tpm2",
    "up",
    "yaml_update_section",
    "yellow",
]
