# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Adapter for the ``terok_sandbox`` wheel (and its re-exports of shield).

Re-exports every symbol terok consumes from terok-sandbox.  Callers
elsewhere in terok import from this module rather than from
``terok_sandbox`` directly — see the package docstring in
[`terok.lib.integrations`][terok.lib.integrations] for the rationale.

Every symbol comes from the wheel's top-level public API.  Pure re-export
boundary — no shim functions, no kwarg massaging.  Shield's high-level
surface is the [`ShieldManager`][terok_sandbox.ShieldManager] /
[`ShieldHooks`][terok_sandbox.ShieldHooks] class pair; shield's command
registry has its own adapter, ``terok.lib.integrations.shield``.

Foundation-layer symbols (``ConfigStack`` / ``ConfigScope`` /
``deep_merge``, ``namespace_state_dir`` / ``namespace_runtime_dir``)
do **not** flow through here — the adapter is the conduit for sibling
**wheels**, while [`terok_util`][terok_util] is a foundation library
imported directly by every layer that needs it.
"""

from terok_sandbox import (  # noqa: F401 — re-exported public API
    DEFAULT_GUEST_SSHD_PORT,
    DEFAULT_SSH_HOST,
    SERVICES_TCP_OPTOUT_YAML,
    CheckVerdict,
    ContainerRuntime,
    CredentialDB,
    DoctorCheck,
    EnvironmentCheck,
    ExecResult,
    GateAuthNotConfigured,
    GateStalenessInfo,
    GitGate,
    Image,
    KrunRuntime,
    LifecycleHooks,
    NoPassphraseError,
    NullRuntime,
    PodmanRuntime,
    RawRunSection,
    RawSSHSection,
    RecoveryStatus,
    Sandbox,
    SandboxConfig,
    SelinuxStatus,
    ServicesMode,
    SetupVerdict,
    Sharing,
    ShieldHooks,
    ShieldManager,
    SSHInitResult,
    SSHKeyRow,
    SSHManager,
    TcpSSHTransport,
    VolumeSpec,
    WrongPassphraseError,
    bold,
    check_environment,
    check_gpu_available,
    check_selinux_status,
    claim_port,
    ensure_infra_keypair,
    gate_use_personal_ssh_default,
    handle_vault_seal,
    handle_vault_to_keyring,
    installed_versions,
    is_ssh_url,
    make_stray_sidecar_check,
    mint_gate_token,
    needs_setup,
    podman_port_resolver,
    provision_session_passphrase,
    public_line_of,
    purge_passphrase_tiers,
    read_stamp,
    red,
    release_port,
    remove_container_state,
    resolve_container_state_dir,
    sandbox_doctor_checks,
    sandbox_uninstall,
    selinux_install_command,
    selinux_install_script,
    stage_line,
    stamp_path,
    systemd_creds_has_tpm2,
    yaml_update_section,
    yellow,
)
from terok_sandbox.paths import (  # noqa: F401 — designated reach-into-private-API site
    plaintext_passphrase_config_path,
)
from terok_sandbox.supervisor.install import (  # noqa: F401 — re-exported
    kill_all_supervisors,
)

__all__ = [
    "CheckVerdict",
    "ContainerRuntime",
    "CredentialDB",
    "DEFAULT_GUEST_SSHD_PORT",
    "DEFAULT_SSH_HOST",
    "DoctorCheck",
    "EnvironmentCheck",
    "ExecResult",
    "GateAuthNotConfigured",
    "GateStalenessInfo",
    "GitGate",
    "Image",
    "KrunRuntime",
    "LifecycleHooks",
    "NoPassphraseError",
    "NullRuntime",
    "PodmanRuntime",
    "RawRunSection",
    "RawSSHSection",
    "RecoveryStatus",
    "SERVICES_TCP_OPTOUT_YAML",
    "SSHInitResult",
    "SSHKeyRow",
    "SSHManager",
    "Sandbox",
    "SandboxConfig",
    "SelinuxStatus",
    "ServicesMode",
    "SetupVerdict",
    "Sharing",
    "ShieldHooks",
    "ShieldManager",
    "TcpSSHTransport",
    "VolumeSpec",
    "WrongPassphraseError",
    "bold",
    "check_environment",
    "check_gpu_available",
    "check_selinux_status",
    "claim_port",
    "ensure_infra_keypair",
    "gate_use_personal_ssh_default",
    "handle_vault_seal",
    "handle_vault_to_keyring",
    "installed_versions",
    "is_ssh_url",
    "kill_all_supervisors",
    "make_stray_sidecar_check",
    "mint_gate_token",
    "needs_setup",
    "plaintext_passphrase_config_path",
    "podman_port_resolver",
    "provision_session_passphrase",
    "public_line_of",
    "purge_passphrase_tiers",
    "read_stamp",
    "red",
    "release_port",
    "remove_container_state",
    "resolve_container_state_dir",
    "sandbox_doctor_checks",
    "sandbox_uninstall",
    "selinux_install_command",
    "selinux_install_script",
    "stage_line",
    "stamp_path",
    "systemd_creds_has_tpm2",
    "yaml_update_section",
    "yellow",
]
